# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deep.mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deep.mobile
  pod 'Moya', '~> 11.0'

  target 'deep.mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'deep.mobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for deep.mobile-tvOS

  target 'deep.mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
